---
- hosts: database
  remote_user: ubuntu
  become: true

  vars:
    username: carlton
    password: cse356cloudcomputingtwitir
    db_name: twitir
    dump_name: twitir.sql
    dump_file: '../courseproject/{{ dump_name }}'
    
  tasks:
    - name: Install mysql-server
      apt:
        name: mysql-server
        state: latest
        update_cache: yes

    - name: Install pip
      apt:
        name: python-pip
        state: latest

    - name: Install mysql_config
      apt:
        name: libmysqlclient-dev
        state: latest

    - name: Update pip
      command: pip install --upgrade pip

    - name: Install mysql python module
      command: pip install MySQL-python

    - name: Create user with ALL and GRANT OPTION
      mysql_user:
        name: '{{ username }}'
        password: '{{ password }}'
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Accept remote connections and add credentials to my.cnf
      blockinfile:
        path: /etc/mysql/my.cnf
        block: |
          [mysqld]
          bind-address = 0.0.0.0

          [mysql]
          user = {{ username }}
          password = {{ password }}

    - name: Create a new database with name {{ db_name }}
      mysql_db:
        name: '{{ db_name }}'
        state: present
        login_user: '{{ username }}'
        login_password: '{{ password }}'

    - name: Copy database dump file
      copy:
        src: '{{ dump_file }}'
        dest: /tmp

    - name: Restore database
      mysql_db:
        name: '{{ db_name }}'
        state: import
        target: /tmp/{{ dump_name }}
        login_user: '{{ username }}'
        login_password: '{{ password }}'

    - name: Restart mysql
      service:
        name: mysql
        state: restarted
