---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install apache2 web server
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Install php
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - php
        - libapache2-mod-php

    - name: Enable apache2 mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
