---
- hosts: mongo
  remote_user: ubuntu
  become: true

  tasks:
    - name: Import the public key used by the package management system
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        state: present

    - name: Create a list file for MongoDB
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        state: present

    - name: Install the MongoDB packages
      apt:
        name: mongodb-org
        update_cache: yes
        state: latest
      notify:
        - start mongodb

    - name: Listen for incoming network connections
      replace:
        path: /etc/mongod.conf
        regexp: 'bindIp: [^\n]*(\n)'
        replace: 'bindIp: 0.0.0.0\n'

  handlers:
    - name: start mongodb
      service:
        name: mongod
        state: started
