---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Set Postfix hostname
      debconf:
        name: postfix
        question: postfix/mailname
        value: "{{ ansible_fqdn }}"
        vtype: string

    - name: Set Postfix option type to Internet Site
      debconf:
        name: postfix
        question: postfix/main_mailer_type
        value: 'Internet Site'
        vtype: string

    - name: Install Postfix and mailutils
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - postfix
        - mailutils
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
