---
- hosts: all
  remote_user: ubuntu

  vars:
    apache_conf: /etc/apache2/apache2.conf
    
  tasks:
    - name: Install apache2
      become: true
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Enable apache2 mod_rewrite
      become: true
      apache2_module:
        name: rewrite
      notify:
        - restart apache2

    - name: Set 'AllowOverride All' in apache2.conf
      become: true
      replace:
        path: '{{ apache_conf }}'
        regexp: '(<Directory\s+/var/www/>\s+.*\s+AllowOverride\s+)None'
        replace: '\1All'

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
