---
- hosts: web
  remote_user: ubuntu

  vars:
    document_root: /var/www/html
    project_name: twitir
    project_dir: '{{ document_root }}/{{ project_name }}'
    apache_conf: /etc/apache2/apache2.conf

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes

    - name: Install apache2
      become: true
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Enable apache2 mod_rewrite
      become: true
      apache2_module:
        name: rewrite
      notify:
        - restart apache2

    - name: Set 'AllowOverride All' in apache2.conf
      become: true
      replace:
        path: '{{ apache_conf }}'
        regexp: '(<Directory\s+/var/www/>\s+.*\s+AllowOverride\s+)None'
        replace: '\1All'

    - name: Add php7.1 repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install php7.1 and some required packages
      become: true
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      with_items:
        - php7.1
        - php7.1-common
        - php7.1-mbstring
        - php7.1-xml
        - zip
        - unzip
        - php7.1-zip
        - php7.1-mysql
        - php-pear
        - php7.1-dev

    - name: Install Composer
      become: true
      apt:
        name: composer
        state: latest
        update_cache: yes

    - name: Stat project_dir
      stat:
        path: '{{ project_dir }}'
      register: project_dir_stat

    - name: Set php7.1 to default
      become: true
      command: update-alternatives --set php /usr/bin/php7.1

    - name: Create Laravel project
      become: true
      composer:
        command: create-project
        arguments: laravel/laravel {{ project_dir }} --no-dev
        prefer_dist: true
        working_dir: '{{ document_root }}'
      when: not project_dir_stat.stat.exists

    - name: Stat '.env.example'
      stat:
        path: '{{ project_dir }}/.env.example'
      register: envexample

    - name: Stat '.env'
      stat:
        path: '{{ project_dir }}/.env'
      register: env

    - name: Rename '.env.example' to '.env'
      become: true
      command: mv '{{ project_dir }}/.env.example' '{{ project_dir }}/.env'
      when:
        - envexample.stat.exists
        - not env.stat.exists
      notify:
        - generate application key

    - name: Configure .env (only for keys that already exist)
      become: true
      replace:
        path: '{{ project_dir }}/.env'
        regexp: '{{ item.key }}=[^\n]*\n'
        replace: '{{ item.key }}={{ item.value }}\n'
      with_items:
        - { key: 'APP_NAME'         , value: 'twitir'                                          }
        - { key: 'APP_DEBUG'        , value: 'false'                                           }
        - { key: 'DB_CONNECTION'    , value: 'mysql'                                           }
        - { key: 'DB_HOST'          , value: 'localhost'                                       }
        - { key: 'DB_PORT'          , value: '3306'                                            }
        - { key: 'DB_DATABASE'      , value: 'twitir'                                          }
        - { key: 'DB_USERNAME'      , value: 'carlton'                                         }
        - { key: 'DB_PASSWORD'      , value: 'cse356cloudcomputingtwitir'                      }
        - { key: 'MAIL_DRIVER'      , value: 'smtp'                                            }
        - { key: 'MAIL_HOST'        , value: 'smtp.googlemail.com'                             }
        - { key: 'MAIL_PORT'        , value: '465'                                             }
        - { key: 'MAIL_USERNAME'    , value: 'cayeung.cse356@gmail.com'                        }
        - { key: 'MAIL_PASSWORD'    , value: 'null'                                            }
        - { key: 'MAIL_ENCRYPTION'  , value: 'ssl'                                             }
        - { key: 'MAIL_FROM_ADDRESS', value: 'noreply@twitir.io'                               }
        - { key: 'MAIL_FROM_NAME'   , value: 'twitir'                                          }

    - name: Directories within the storage and the bootstrap/cache directories should be writable by your web server or Laravel will not run
      become: true
      file:
        path: '{{ project_dir }}/{{ item }}'
        owner: www-data
        group: www-data
        state: directory
        recurse: yes
      with_items:
        - storage
        - bootstrap/cache
      when:
        - not project_dir_stat.stat.exists

    - name: Set document root to Laravel's /public directory
      become: true
      replace:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '(DocumentRoot\s+)(.*)(\n)'
        replace: '\1{{ project_dir }}/public\3'
      notify:
        - restart apache2

    - name: Import the public key used by the package management system
      become: true
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        state: present

    - name: Create a list file for MongoDB
      become: true
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        state: present

    - name: Install the MongoDB packages
      become: true
      apt:
        name: mongodb-org
        update_cache: yes
        state: latest

    - name: Install MongoDB PHP Driver
      become: true
      pear:
        name: pecl/mongodb
        state: present

    - name: Add mongodb.so extension to php.ini
      become: true
      lineinfile:
        path: '{{ item }}'
        line: 'extension=mongodb.so'
      with_items:
        - /etc/php/7.1/apache2/php.ini
        - /etc/php/7.1/cli/php.ini

    - name: Add mongodb to .env
      become: true
      lineinfile:
        path: '{{ project_dir }}/.env'
        line: '{{ item }}'
      with_items:
        - MONGO_HOST=localhost
        - MONGO_PORT=27017

    - name: Set Postfix hostname
      become: true
      debconf:
        name: postfix
        question: postfix/mailname
        value: "{{ ansible_fqdn }}"
        vtype: string

    - name: Set Postfix option type to Internet Site
      become: true
      debconf:
        name: postfix
        question: postfix/main_mailer_type
        value: 'Internet Site'
        vtype: string

    - name: Install Postfix and mailutils
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - postfix
        - mailutils

    - name: Restart apache2
      become: true
      service:
        name: apache2
        state: restarted

  handlers:
    - name: restart apache2
      become: true
      service:
        name: apache2
        state: restarted

    - name: generate application key
      become: true
      command: php artisan key:generate
      args:
        chdir: '{{ project_dir }}'
